let userScore= 0;
let computerScore = 0;
let msg=document.querySelector(".msg-box");
let hands=document.querySelectorAll(".hand");

let userScorePara=document.querySelector("#user-score");
let computerScorePara=document.querySelector("#computer-score");
;

let genComputerChoice=( ) =>{
    const option=["stone","paper","scissors"];
    const randomIdx= Math.floor(Math.random()*3);
    return option[randomIdx];//value generated by computer
};

const drawGame=()=>{
   console.log("Draw The Game");
  msg.innerText="Draw The Game";
    msg.style.background="black";
};

let showWinner=(userWin)=>{
   if(userWin){
    console.log("you win!!");
    msg.innerText="You Win";
    msg.style.background="green";
    userScore++;
    userScorePara.innerText=userScore;
   }else { 
    computerScore++;
    computerScorePara.innerText=userScore;
    msg.innerText="You Lose!!";
    msg.style.background="red";

   }
};

let playGame =(userChoice)=>{

  console.log("User choice = ", userChoice);
  const computerChoice = genComputerChoice();
  console.log("computer choice = ", computerChoice);

  if(userChoice===computerChoice){
    drawGame();
  }else {
    let userWin=true;
    if(userChoice==="rock"){
       userWin = computerChoice==="paper"? false: true;
    }else if(userChoice==="paper"){
      userWin= computerChoice==="scissor"? false:true;
    }else {
       userWin= computerChoice==="rock"? false:true;
    }
   showWinner(userWin);
}
};

hands.forEach((hand) =>{
  hand.addEventListener("click",()=>{
    let userChoice = hand.getAttribute("id");
    playGame(userChoice);
   
  });
});
